schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        disease_gene: 
          type: integer
        disease_gene_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        healthprof: 
          type: integer
        id: 
          type: integer
        institution: 
          type: integer
        institution_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        natural_variant: 
          type: integer
        natural_variant_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        notes: 
          type: string
        onset: 
          type: integer
        patient: 
          type: integer
        patient_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        rec_name: 
          type: string
        variant_phenotype: 
          type: integer
        variant_phenotype_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      - create_date: '2024-08-23T05:05:00.086896'
        create_uid: 1
        create_uid_:
          id: 1
          name: Administrator
        disease_gene: 41
        disease_gene_:
          id: 41
          name: AAVS1:adeno-associated virus integration site 1
        healthprof: 1
        id: 21
        institution: 1
        institution_:
          id: 1
          name: elyas
        natural_variant: 81160
        natural_variant_:
          id: 81160
          name: 'vr02 : aa-change'
        notes: some notes
        onset: 1
        patient: 4
        patient_:
          id: 4
          name: elyas
        rec_name: '21'
        variant_phenotype: 39739
        variant_phenotype_:
          id: 39739
          name: DI-00001:HDS10 mitochondrial disease
        write_date: '2024-08-23T05:12:25.923596'
        write_uid: 1
        write_uid_:
          id: 1
          name: Administrator
    errors: null
    pagination: null
    status: 201
    success_message: null
