schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        company:
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        date:
          type: string
          format: date
        description: 
          type: string
        id:
          type: integer
        journal:
          type: integer
        journal_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        lines:
          type: array
          nullable: true
        number:
          type: string
        origin:
          type: string
        origin_: 
          type: object
        period:
          type: integer
        period_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        post_date: 
          type: string
          format: date
        post_number: 
          type: string
        rec_name:
          type: string
        state:
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      create_date: '2024-04-18T04:45:21.629821'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      company: 1
      company_:
        id: 1
        name: Party 1
      date: '2026-01-27'
      description: some description here
      id: 2
      journal: 13
      journal_:
        id: 13
        name: Statement
      lines: []
      number: '1'
      origin: account.move,-1
      origin_: {}
      period: 79
      period_:
        id: 79
        name: '1'
      post_date: 
      post_number: 
      rec_name: '1'
      state: draft
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
