openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: currency
    description: currency - currency data management.
paths:
  '/currency/currencies/search':
    $ref: 'get_currency.yaml'
  '/currency/currencies':
    $ref: 'post_delete_currency.yaml'
  '/currency/currencies/{obj_id}':
    $ref: 'get_put_currency_by_id.yaml'
  