openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: leave type
    description: hr holiday - leave types management.
paths:
  '/hr-holiday/leave-types/search':
    $ref: 'get_leave_type.yaml'
  '/hr-holiday/leave-types':
    $ref: 'post_delete_leave_type.yaml'
  '/hr-holiday/leave-types/{obj_id}':
    $ref: 'get_put_leave_type_by_id.yaml'
