schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        id: 
          type: integer
        purchase_invoice_method: 
          type: string
        purchase_process_after: 
          type: string
          format: date
        purchase_sequence: 
          type: integer
        purchase_sequence_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        rec_name: 
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      create_date: '2024-09-20T15:57:49.369402'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      id: 1
      purchase_invoice_method: order
      purchase_process_after: 
      purchase_sequence: 29
      purchase_sequence_:
        id: 29
        name: Purchase
      rec_name: 
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
