openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: variant
    description: variant - variant data management.
paths:
  '/product/variants/search':
    $ref: 'get_variant.yaml'
  '/product/variants/sales/search':
    $ref: 'get_variant_sales.yaml'
  '/product/variants':
    $ref: 'post_delete_variant.yaml'
  '/product/variants/{obj_id}':
    $ref: 'get_put_variant_by_id.yaml'
  '/product/variants/{obj_id}/modify-cost-price':
    $ref: 'get_modify_cost_price_by_id.yaml'
  '/product/variants/{obj_id}/recompute-cost-price':
    $ref: 'get_recompute_cost_price_by_id.yaml'
  
  