openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: reporting sale per customer category
    description: reporting sale per customer category - reporting sale per customer category data management.
paths:
  '/sale/reporting/sales-per-customer/search':
    $ref: 'post_reporting_sale_per_customer_category.yaml'
  '/sale/reporting/sales-per-customer-timeseries/search':
    $ref: 'post_reporting_sale_per_customer_category_timeseries.yaml'
  