schema:
  properties:
    data:
      type: array
      properties:
        code:
          type: string
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        active: 
          type: boolean
        aetitle: 
          type: string
        id: 
          type: integer
        name: 
          type: string
        product:
          type: integer
        product_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        rec_name: 
          type: string
        test_type: 
          type: integer
        test_type_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        worklist_template: 
          type: integer
        worklist_template_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      active: true
      aetitle: study_test
      code: '009'
      create_date: '2024-08-19T15:26:16.895060'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      id: 1
      name: new_study
      product: 62
      product_:
        id: 62
        name: albendazole
      rec_name: new_study
      test_type: 5
      test_type_:
        id: 5
        name: Digital Radiography
      worklist_template: 1
      worklist_template_:
        id: 1
        name: worklist template
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
