openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: location
    descriptiolocationn: location - location data management.
paths:
  '/health-caldav/calendar-locations/search':
    $ref: 'get_location.yaml'
  '/health-caldav/calendar-locations':
    $ref: 'post_delete_location.yaml'
  '/health-caldav/calendar-locations/{obj_id}':
    $ref: 'get_put_location_by_id.yaml'
  