openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: pathology group
    description: pathology group - pathology group data management.
paths:
  '/health/pathology-groups/search':
    $ref: 'get_pathology_group.yaml'
  '/health/pathology-groups':
    $ref: 'post_delete_pathology_group.yaml'
  '/health/pathology-groups/{obj_id}':
    $ref: 'get_put_pathology_group_by_id.yaml'
  