properties:
  create_date: 
    type: string 
    format: date 
  create_uid: 
    type: integer
  default_cost_price_method:
    type: string
  product_sequence: 
    type: integer
  rec_name: 
    type: string
  template_sequence: 
    type: integer
  write_date: 
    type: string
    format: date
  write_uid: 
    type: integer
   
required:
        
example:
  create_date: '2024-05-08T16:06:02.597623'
  create_uid: 1
  default_cost_price_method: fixed
  product_sequence: null
  rec_name: null
  template_sequence: null
  write_date: null
  write_uid: null