schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        assignation_required: 
          type: boolean
        company: 
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        cost_price: 
          type: integer
        cost_price_required: 
          type: boolean
        currency: 
          type: integer
        currency_: 
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        delay: 
          type: string
          format: duration
        effective_date: 
          type: string 
          format: date 
        from_location: 
          type: integer
        from_location_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        id: 
          type: integer
        internal_quantity: 
          type: integer
        lot: 
          type: integer
        lot_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        origin: 
          type: string 
        origin_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        origin_planned_date: 
          type: string 
          format: date 
        planned_date: 
          type: string 
          format: date 
        product: 
          type: integer
        product_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        product_cost_price: 
          type: number
          format: decimal
        product_uom_category: 
          type: integer
        product_uom_category_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        quantity: 
          type: integer
        rec_name: 
          type: string
        shipment: 
          type: string
        state: 
          type: string
        to_location: 
          type: integer
        to_location_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        unit: 
          type: integer
        unit_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        unit_price: 
          type: number
          format: decimal
        unit_price_company: 
          type: number
          format: decimal
        unit_price_required: 
          type: boolean
        unit_price_updated: 
          type: boolean
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      assignation_required: false
      company: 1
      company_:
        id: 1
        name: Milestone
      cost_price: 0
      cost_price_required: true
      create_date: '2024-08-10T17:06:31.344034'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      currency: 
      currency_: {}
      delay: 
      effective_date: '2024-08-10'
      from_location: 4
      from_location_:
        id: 4
        name: Lost and Found
      id: 5
      internal_quantity: 1
      lot: 3
      lot_:
        id: 3
        name: '1'
      origin: stock.inventory.line,1
      origin_:
        id: 1
        name: acetazolamide - 1
      origin_planned_date: 
      planned_date: 
      product: 384
      product_:
        id: 384
        name: acetazolamide
      product_cost_price: 
      product_uom_category: 1
      product_uom_category_:
        id: 1
        name: Units
      quantity: 1
      rec_name: 1 u acetazolamide
      shipment: 
      state: done
      to_location: 2
      to_location_:
        id: 2
        name: Output Zone
      unit: 1
      unit_:
        id: 1
        name: Unit
      unit_price: 
      unit_price_company: 
      unit_price_required: false
      unit_price_updated: true
      write_date: '2024-08-10T17:06:31.344034'
      write_uid: 0
      write_uid_:
        id: 0
        name: Root
    errors: null
    pagination: null
    status: 201
    success_message: null
