schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        action: 
          type: string
        action_:
          entity: 
            type: string
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        active: 
          type: boolean
        groups: 
          type: array
        icon: 
          type: integer
        icon_: 
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        id: 
          type: integer
        keywords:
          type: array
          properties:
            action: 
              type: integer
            action_:
              $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
            create_date: 
              type: string 
              format: date 
            create_uid: 
              type: integer
            create_uid_:
              $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
            id: 
              type: integer
            keyword: 
              type: string
            model: 
              type: string
            model_:
              entity: 
                type: string
              $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
            rec_name: 
              type: string
            write_date:
              type: string
              format: date 
            write_uid:
              type: integer
            write_uid_:
              $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        name: 
          type: string
        rec_name: 
          type: string
        records: 
          type: string
        type: 
          type: string
        usage: 
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      action: ir.action.act_window,1
      action_:
        entity: ir.action.act_window
        id: 1
        name: Icons
      active: true
      create_date: '2024-06-24T12:35:58.699428'
      create_uid: 0
      create_uid_:
        id: 0
        name: Root
      groups: []
      icon: 
      icon_: {}
      id: 1
      keywords:
      - action: 1
        action_:
          id: 1
          name: Icons
        create_date: '2024-06-24T12:35:58.699428'
        create_uid: 0
        create_uid_:
          id: 0
          name: Root
        id: 1
        keyword: tree_open
        model: ir.ui.menu,3
        model_:
          entity: ir.ui.menu
          id: 3
          name: Administration / User Interface / Icons
        rec_name: '1'
        write_date: 
        write_uid: 
        write_uid_: {}
      name: Icons
      rec_name: Icons
      records: selected
      type: ir.action.act_window
      usage: 
      write_date: '2024-06-24T12:35:58.699428'
      write_uid: 0
      write_uid_:
        id: 0
        name: Root
    errors: null
    pagination: null
    status: 201
    success_message: null
