openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: reporting sale per product
    description: reporting sale per product - reporting sale per product data management.
paths:
  '/sale/reporting/sales-per-product/search':
    $ref: 'post_reporting_sale_per_product.yaml'
  '/sale/reporting/sales-per-product-timeseries/search':
    $ref: 'post_reporting_sale_per_product_timeseries.yaml'
  
  