openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: sequence
    description: sequence - sequence data management.
paths:
  '/administration/sequences/search':
    $ref: 'get_sequence.yaml'
  '/administration/sequences':
    $ref: 'post_delete_sequence.yaml'
  '/administration/sequences/{obj_id}':
    $ref: 'get_put_sequence_by_id.yaml'
    
  