openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: account type
    description: account type - account type data management.
paths:
  '/financial-accounting/account-types/search':
    $ref: 'get_account_type.yaml'
  '/financial-accounting/account-types':
    $ref: 'post_delete_account_type.yaml'
  '/financial-accounting/account-types/{obj_id}':
    $ref: 'get_put_account_type_by_id.yaml'
  