openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: action report
    description: action report - action report data management.
paths:
  '/administration/reports/search':
    $ref: 'post_search_action_report.yaml'
  '/administration/reports':
    $ref: 'post_delete_action_report.yaml'
  '/administration/reports/{obj_id}':
    $ref: 'get_put_action_report_by_id.yaml'
  '/administration/reports/execute/{report_name}':
    $ref: 'post_execute_action_report.yaml'

    
  