schema:
  properties:
    data:
      type: array
      properties:
        active:
          type: boolean
        code:
          type: string
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        digits:
          type: integer
        id:
          type: integer
        name:
          type: string
        numeric_code:
          type: string
        rate:
          type: number
          format: decimal
        rates:
          type: array
          properties:
            date: 
              type: string
              format: date
            id: 
              type: integer
            rate: 
              type: number
              format: decimal
        rec_name:
          type: string
        rounding:
          type: number
          format: float
        symbol:
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      active: true
      code: AFN
      create_date: '2024-04-18T04:45:21.629821'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      digits: 2
      id: 1
      name: Afghani
      numeric_code: ''
      rate: 0
      rates: []
      rec_name: Afghani
      rounding: 0.01
      symbol: AFN
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
