openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: orthanc server config
    description: orthanc server config - orthanc server config data management.
paths:
  '/health-orthanc/servers/search':
    $ref: 'get_orthanc_server_config.yaml'
  '/health-orthanc/servers':
    $ref: 'post_delete_orthanc_server_config.yaml'
  '/health-orthanc/servers/{obj_id}':
    $ref: 'get_put_orthanc_server_config_by_id.yaml'
  