openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: new born
    description: new born - new born data management.
paths:
  '/health-pediatrics/new-born/search':
    $ref: 'get_new_born.yaml'
  '/health-pediatrics/new-born':
    $ref: 'post_delete_new_born.yaml'
  '/health-pediatrics/new-born/{obj_id}':
    $ref: 'get_put_new_born_by_id.yaml'
  '/health-pediatrics/new-born/{obj_id}/sign':
    $ref: 'get_sign.yaml'
  