schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        currencies:
          type: array
        currency:
          type: integer
        currency_:
          type: object
          id:
            type: integer
          name:
            type: string
        day:
          type: integer
        frequency:
          type: string
        id:
          type: integer
        last_update:
          type: string
          format: date
        rec_name:
          type: string
        source:
          type: string
        weekday:
          type: integer
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      create_date: '2024-04-18T06:56:45.664564'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      currencies: []
      currency: 1
      currency_:
        id: 1
        name: Afghani
      day: 
      frequency: daily
      id: 4
      last_update: '2024-04-27'
      rec_name: '4'
      source: ecb
      weekday: 
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
