openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: scheduled rate update
    description: scheduled rate update - scheduled rate update data management.

paths:
  '/currency/scheduled-rate-updates/search':
    $ref: 'get_scheduled_rate_updates.yaml'
  '/currency/scheduled-rate-updates':
    $ref: 'post_delete_scheduled_rate_updates.yaml'
  '/currency/scheduled-rate-updates/{obj_id}':
    $ref: 'get_put_scheduled_rate_updates_by_id.yaml'
