openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: reports
    description: reports - reports data management.
paths:
  '/financial-accounting/reports/general-ledger/default-context':
    $ref: 'get_general_ledger.yaml'
  '/financial-accounting/reports/general-ledger':
    $ref: 'post_general_ledger.yaml'
  '/financial-accounting/reports/balance-sheet/default-context':
    $ref: 'get_balance_sheet.yaml'
  '/financial-accounting/reports/balance-sheet':
    $ref: 'post_balance_sheet.yaml'
  '/financial-accounting/reports/income-statement/default-context':
    $ref: 'get_income_statement.yaml'
  '/financial-accounting/reports/income-statement':
    $ref: 'post_income_statement.yaml'
  '/financial-accounting/reports/chart-of-account/default-context':
    $ref: 'get_chart_of_account.yaml'
  '/financial-accounting/reports/chart-of-account':
    $ref: 'post_chart_of_account.yaml'
  '/financial-accounting/reports/chart-of-tax-codes/default-context':
    $ref: 'get_chart_of_tax_codes.yaml'
  '/financial-accounting/reports/chart-of-tax-codes':
    $ref: 'post_chart_of_tax_codes.yaml'
  '/financial-accounting/reports/aged-balance/default-context':
    $ref: 'get_aged_balance.yaml'
  '/financial-accounting/reports/aged-balance':
    $ref: 'post_aged_balance.yaml'
  '/financial-accounting/reports/journal-cash/default-context':
    $ref: 'get_journal_cash.yaml'
  '/financial-accounting/reports/journal-cash':
    $ref: 'post_journal_cash.yaml'
  '/financial-accounting/reports/general-ledger-lines/default-context':
    $ref: 'get_general_ledger_lines.yaml'
  '/financial-accounting/reports/general-ledger-lines':
    $ref: 'post_general_ledger_lines.yaml'
  '/financial-accounting/reports/general-ledger-account-parties/default-context':
    $ref: 'get_general_ledger_account_parties.yaml'
  '/financial-accounting/reports/general-ledger-account-parties':
    $ref: 'post_general_ledger_account_parties.yaml'
  '/financial-accounting/reports/cashflow/default-context':
    $ref: 'get_cashflow.yaml'
  '/financial-accounting/reports/cashflow':
    $ref: 'post_cashflow.yaml'
