openapi: 3.1.0
info:
  description: >
  contact:
    name: API Support
    email: shadab@gmail.com
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: statement journal
    description: statement journal - statement journal data management.
paths:
  '/financial-accounting/statement-journals/search':
    $ref: 'post_delete_statement_journal.yaml'
  '/financial-accounting/statement-journals':
    $ref: 'post_statement_journal.yaml'
  '/financial-accounting/statement-journals/{obj_id}':
    $ref: 'get_put_statement_journal_by_id.yaml'