openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: dentistry procedure
    description: dentistry procedure - dentistry procedure data management.
paths:
  '/health-dentistry/dentistry-procedures/search':
    $ref: 'get_dentistry_procedure.yaml'
  '/health-dentistry/dentistry-procedures':
    $ref: 'post_delete_dentistry_procedure.yaml'
  '/health-dentistry/dentistry-procedures/{obj_id}':
    $ref: 'get_put_dentistry_procedure_by_id.yaml'
  