openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: employee
    description: employee - employee data management.
paths:
  '/company/employees/search':
    $ref: 'get_employee.yaml'
  '/company/employees':
    $ref: 'post_delete_employee.yaml'
  '/company/employees/{obj_id}':
    $ref: 'get_put_employee_by_id.yaml'
  