get:
      tags:
        - configuration
      summary: Get one configuration.
      description: Get one configuration.
      operationId: getConfigurationById
      parameters:
        - name: obj_id
          in: path
          schema:
            type: integer
          rquired: true
          example: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        create_date: 
                          type: string 
                          format: date 
                        create_uid: 
                          type: integer
                        create_uid_:
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        default_cost_price_method:
                          type: string
                        id: 
                          type: integer
                        product_sequence: 
                          type: integer
                        product_sequence_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        rec_name: 
                          type: string
                        template_sequence: 
                          type: integer
                        template_sequence_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        write_date: 
                          type: string
                          format: date
                        write_uid: 
                          type: integer
                        write_uid_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                    errors:
                      type: object
                    pagination:
                      items:
                        type: object
                      properties:
                        page:
                          type: integer
                        per_page:
                          type: integer
                        total_pages:
                          type: integer
                        total_records:
                          type: integer
                    status:
                      type: integer
                    success_message:
                      type: string
                      nullable: true
              example:
                data:
                  create_date: '2024-05-08T16:06:02.597623'
                  create_uid: 1
                  create_uid_:
                    id: 1
                    name: Administrator
                  default_cost_price_method: fixed
                  id: 1
                  product_sequence: 
                  product_sequence_: {}
                  rec_name: 
                  template_sequence: 
                  template_sequence_: {}
                  write_date: 
                  write_uid: 
                  write_uid_: {}
                error: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '../../../api_doc.yaml#/components/schemas/HTTP401'
        '404':
          description: 404 Not Found.
          content:
            application/json:
              schema:
                $ref: '../../../api_doc.yaml#/components/schemas/HTTP404'

put:
      tags:
        - configuration
      summary: Update a configuration.
      description: Update a configuration.
      operationId: updateConfigurationById
      parameters:
        - name: obj_id
          rquired: true
          in: path
          schema:
            type: integer
          example: 19
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              $ref: '../../../api_doc.yaml#/components/schemas/UpdateProductConfiguration'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  properties:
                    data:
                      type: object
                      properties:
                        create_date: 
                          type: string 
                          format: date 
                        create_uid: 
                          type: integer
                        create_uid_:
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        default_cost_price_method:
                          type: string
                        id: 
                          type: integer
                        product_sequence: 
                          type: integer
                        product_sequence_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        rec_name: 
                          type: string
                        template_sequence: 
                          type: integer
                        template_sequence_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                        write_date: 
                          type: string
                          format: date
                        write_uid: 
                          type: integer
                        write_uid_: 
                          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
                    errors:
                      type: object
                    pagination:
                      items:
                        type: object
                      properties:
                        page:
                          type: integer
                        per_page:
                          type: integer
                        total_pages:
                          type: integer
                        total_records:
                          type: integer
                    status:
                      type: integer
                    success_message:
                      type: string
              example:
                data:
                  create_date: '2024-05-08T16:06:02.597623'
                  create_uid: 1
                  create_uid_:
                    id: 1
                    name: Administrator
                  default_cost_price_method: fixed
                  id: 1
                  product_sequence: 
                  product_sequence_: {}
                  rec_name: 
                  template_sequence: 
                  template_sequence_: {}
                  write_date: 
                  write_uid: 
                  write_uid_: {}
                errors: null
                pagination: null
                status: 200
                success_message: null
        '401':
          description: >-
            401 Unauthorized: The server could not verify that you are
            authorized to access the URL requested. You either supplied the
            wrong credentials (e.g. a bad password), or your browser doesn't
            understand how to supply the credentials required.
          content:
            application/json:
              schema:
                $ref: '../../../api_doc.yaml#/components/schemas/HTTP401'
    