schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        default_cost_price_method:
          type: string
        id: 
          type: integer
        product_sequence: 
          type: integer
        product_sequence_: 
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        rec_name: 
          type: string
        template_sequence: 
          type: integer
        template_sequence_: 
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        write_date: 
          type: string
          format: date
        write_uid: 
          type: integer
        write_uid_: 
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      create_date: '2024-04-18T04:45:21.629821'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
