openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: config wizard items
    description: config wizard items - config wizard items data management.
paths:
  '/administration/config-wizard-items/search':
    $ref: 'get_config_wizard_items.yaml'
  '/administration/config-wizard-items':
    $ref: 'post_delete_config_wizard_items.yaml'
  '/administration/config-wizard-items/{obj_id}':
    $ref: 'get_put_config_wizard_items_by_id.yaml'
  