schema:
  properties:
    data:
      type: array
      properties:
        active: 
          type: boolean
        company: 
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        id: 
          type: integer
        name: 
          type: string
        number_increment: 
          type: integer
        number_next: 
          type: integer
        padding: 
          type: integer
        prefix: 
          type: string
        preview: 
          type: string
        rec_name: 
          type: string
        sequence_type: 
          type: integer
        sequence_type_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType' 
        suffix: 
          type: string
        type: 
          type: string
        write_date: 
          type: string
          format: date
        write_uid: 
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      active: true
      company: 1
      company_:
        id: 1
        name: Milestone
      create_date: '2024-04-21T04:09:45.808043'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      id: 2
      name: customers
      number_increment: 1
      number_next: 3
      padding: 0
      prefix: ''
      preview: '3'
      rec_name: customers
      sequence_type: 7
      sequence_type_:
        id: 7
        name: Invoice
      suffix: ''
      type: incremental
      write_date: '2024-05-05T11:12:40.042995'
      write_uid: 1
      write_uid_:
        id: 1
        name: Administrator
    errors: null
    pagination: null
    status: 201
    success_message: null
