schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        company: 
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        contact_address: 
          type: integer
        contact_address_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        customer: 
          type: integer
        customer_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        customer_location: 
          type: integer
        customer_location_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        delay: 
          type: string
          format: duration
        done_by: 
          type: integer
        done_by_: 
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        effective_date:
          type: string
          format: date
        id: 
          type: integer
        incoming_moves:
          type: array
          properties:
            assignation_required: 
              type: boolean
            company:  
              type: integer
            company_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            cost_price: 
              type: number
              format: decimal
            cost_price_required: 
              type: boolean
            create_date: 
              type: string 
              format: date 
            create_uid: 
              type: integer
            create_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            currency: 
              type: integer
            currency_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            delay: 
              type: string
              format: duration
            effective_date: 
              type: string
              format: date
            from_location: 
              type: integer
            from_location_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            id: 
              type: integer
            internal_quantity: 
              type: integer
            lot: 
              type: integer
            lot_: 
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            origin: 
              type: string
            origin_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            origin_planned_date: 
              type: string
              format: date
            planned_date: 
              type: string
              format: date
            product: 
              type: integer
            product_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            product_cost_price: 
              type: number
              format: decimal
            product_uom_category: 
              type: integer
            product_uom_category_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            quantity: 
              type: integer
            rec_name: 
              type: string
            shipment: 
              type: string
            state: 
              type: string
            to_location: 
              type: integer
            to_location_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            unit: 
              type: integer
            unit_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            unit_price: 
              type: number
              format: decimal
            unit_price_company: 
              type: number
              format: decimal
            unit_price_required: 
              type: boolean
            unit_price_updated: 
              type: boolean
            write_date:
              type: string
              format: date 
            write_uid:
              type: integer
            write_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        inventory_moves: 
          type: array
        moves:
          type: array
          properties:
            assignation_required: 
              type: boolean
            company: 
              type: integer
            company_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            cost_price: 
              type: number
              format: decimal
            cost_price_required: 
              type: boolean
            create_date: 
              type: string 
              format: date 
            create_uid: 
              type: integer
            create_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            currency: 
              type: integer
            currency_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            delay:  
              type: string
              format: duration
            effective_date: 
              type: string
              format: date
            from_location: 
              type: integer
            from_location_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            id: 
              type: integer
            internal_quantity: 
              type: integer
            lot:
              type: integer
            lot_: 
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            origin: 
              type: string
            origin_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            origin_planned_date: 
            planned_date: 
              type: string
              format: date
            product:  
              type: integer
            product_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            product_cost_price: 
              type: number
              format: decimal
            product_uom_category: 
              type: integer
            product_uom_category_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            quantity: 
              type: integer
            rec_name: 
              type: string
            shipment: 
              type: string
            state: 
              type: string
            to_location: 
              type: integer
            to_location_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            unit: 
              type: integer
            unit_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            unit_price: 
              type: number
              format: decimal
            unit_price_company: 
              type: number
              format: decimal
            unit_price_required: 
              type: boolean
            unit_price_updated: 
              type: boolean
            write_date:
              type: string
              format: date 
            write_uid:
              type: integer
            write_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        number:
          type: string
        origin_planned_date: 
        origins: 
          type: string
        planned_date: 
          type: string
        rec_name: 
          type: string
        received_by: 
          type: integer
        received_by_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        reference: 
          type: string
        state: 
          type: string
        warehouse:  
          type: integer
        warehouse_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        warehouse_input: 
          type: integer
        warehouse_input_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        warehouse_storage: 
          type: integer
        warehouse_storage_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      company: 1
      company_:
        id: 1
        name: Milestone
      contact_address: 1
      contact_address_:
        id: 1
        name: Milestone
      create_date: '2024-08-10T10:42:00.985666'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      customer: 1
      customer_:
        id: 1
        name: Milestone
      customer_location: 7
      customer_location_:
        id: 7
        name: Customer
      delay: 2764800
      done_by: 
      done_by_: {}
      effective_date: '2024-08-29'
      id: 1
      incoming_moves:
      - assignation_required: false
        company: 1
        company_:
          id: 1
          name: Milestone
        cost_price: 
        cost_price_required: true
        create_date: '2024-08-10T10:42:00.985666'
        create_uid: 1
        create_uid_:
          id: 1
          name: Administrator
        currency: 1
        currency_:
          id: 1
          name: Afghani
        delay: '0:00:00'
        effective_date: 
        from_location: 7
        from_location_:
          id: 7
          name: Customer
        id: 4
        internal_quantity: 1
        lot: 
        lot_: {}
        origin: stock.move,1
        origin_:
          id: 1
          name: 1 u aciclovir
        origin_planned_date: 
        planned_date: '2024-07-28'
        product: 388
        product_:
          id: 388
          name: acetic acid
        product_cost_price: 
        product_uom_category: 1
        product_uom_category_:
          id: 1
          name: Units
        quantity: 1
        rec_name: 1 u acetic acid
        shipment: stock.shipment.out.return,1
        state: draft
        to_location: 1
        to_location_:
          id: 1
          name: Input Zone
        unit: 1
        unit_:
          id: 1
          name: Unit
        unit_price: 2000
        unit_price_company: 2000
        unit_price_required: true
        unit_price_updated: true
        write_date: '2024-08-10T10:42:00.985666'
        write_uid: 1
        write_uid_:
          id: 1
          name: Administrator
      inventory_moves: []
      moves:
      - assignation_required: false
        company: 1
        company_:
          id: 1
          name: Milestone
        cost_price: 
        cost_price_required: true
        create_date: '2024-08-10T10:42:00.985666'
        create_uid: 1
        create_uid_:
          id: 1
          name: Administrator
        currency: 1
        currency_:
          id: 1
          name: Afghani
        delay: '0:00:00'
        effective_date: 
        from_location: 7
        from_location_:
          id: 7
          name: Customer
        id: 4
        internal_quantity: 1
        lot: 
        lot_: {}
        origin: stock.move,1
        origin_:
          id: 1
          name: 1 u aciclovir
        origin_planned_date: 
        planned_date: '2024-07-28'
        product: 388
        product_:
          id: 388
          name: acetic acid
        product_cost_price: 
        product_uom_category: 1
        product_uom_category_:
          id: 1
          name: Units
        quantity: 1
        rec_name: 1 u acetic acid
        shipment: stock.shipment.out.return,1
        state: draft
        to_location: 1
        to_location_:
          id: 1
          name: Input Zone
        unit: 1
        unit_:
          id: 1
          name: Unit
        unit_price: 2000
        unit_price_company: 2000
        unit_price_required: true
        unit_price_updated: true
        write_date: '2024-08-10T10:42:00.985666'
        write_uid: 1
        write_uid_:
          id: 1
          name: Administrator
      number: '1'
      origin_planned_date: 
      origins: 1 u aciclovir
      planned_date: '2024-07-28'
      rec_name: '1'
      received_by: 2
      received_by_:
        id: 2
        name: Milestone
      reference: '123'
      state: draft
      warehouse: 5
      warehouse_:
        id: 5
        name: Warehouse
      warehouse_input: 1
      warehouse_input_:
        id: 1
        name: Input Zone
      warehouse_storage: 3
      warehouse_storage_:
        id: 3
        name: Storage Zone
      write_date: '2024-08-10T10:42:00.985666'
      write_uid: 1
      write_uid_:
        id: 1
        name: Administrator
    errors: null
    pagination: null
    status: 201
    success_message: null
