openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: shipment out return
    description: shipment out return - shipment out return data management.
paths:
  '/stock/customer-returns/search':
    $ref: 'get_shipment_out_return.yaml'
  '/stock/customer-returns':
    $ref: 'post_delete_shipment_out_return.yaml'
  '/stock/customer-returns/{obj_id}':
    $ref: 'get_put_shipment_out_return_by_id.yaml'
  '/stock/customer-returns/{obj_id}/draft':
    $ref: 'get_draft.yaml'
  '/stock/customer-returns/{obj_id}/cancel':
    $ref: 'get_cancel.yaml'
  '/stock/customer-returns/{obj_id}/recieve':
    $ref: 'get_recieve.yaml'
  