schema:
  properties:
    data:
      type: object
      properties:
        id:
          type: integer
        rec_name:
          type: string
        name:
          type: string
        sequence:
          type: integer
        company:
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        create_date:
          type: string
          format: date-time
        create_uid:
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        write_date:
          type: string
          format: date-time
          nullable: true
        write_uid:
          type: integer
          nullable: true
    error:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
  data:
    id: 2
    rec_name: Exceeds expectations
    name: Exceeds expectations
    sequence: 10
    company: 1
    company_:
      id: 1
      name: Demo Company
    create_date: '2026-04-01T10:00:00'
    create_uid: 1
    create_uid_:
      id: 1
      name: Administrator
    write_date: null
    write_uid: null
  error: null
  pagination: null
  status: 200
  success_message: null
