openapi: 3.1.0
servers:
  - url: 'http://api-alpha.umbrellaerp.com'
tags:
  - name: operational sector
    description: operational sector - operational sector data management.
paths:
  '/health/operational-sectors/search':
    $ref: 'get_operational_sector.yaml'
  '/health/operational-sectors':
    $ref: 'post_delete_operational_sector.yaml'
  '/health/operational-sectors/{obj_id}':
    $ref: 'get_put_operational_sector_by_id.yaml'
  