schema:
  properties:
    data:
      type: array
      properties:
        code:   
          type: string
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        extra_info: 
          type: string
        id: 
          type: integer
        institution: 
          type: integer
        institution_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
          
        name: 
          type: string
        rec_name: 
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      code: e009
      create_date: '2024-07-27T05:34:29.683531'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      extra_info: ''
      id: 1
      institution: 1
      institution_:
        id: 1
        name: Milestone
      name: emergency
      rec_name: emergency
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
