type: object
properties:
  data:
    type: object
    nullable: true
  errors:
    type: object
    nullable: true
  pagination:
    type: object
    nullable: true
  status:
    type: integer
  success_message:
    type: string
    nullable: true
