schema:
  properties:
    data:
      type: array
      properties:
        create_date: 
          type: string 
          format: date 
        create_uid: 
          type: integer
        create_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        company: 
          type: integer
        company_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        date: 
          type: string 
          format: date
        empty_quantity: 
          type: string 
        id: 
          type: integer
        lines:
          type: array
          properties:
            create_date: 
              type: string 
              format: date 
            create_uid: 
              type: integer
            create_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            expected_quantity: 
              type: integer
            id: 
              type: integer
            inventory: 
              type: integer
            inventory_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            inventory_date: 
              type: string 
              format: date
            inventory_location: 
              type: integer
            inventory_location_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            inventory_state: 
              type: string
            moves: 
              type: array
            product: 
              type: integer
            product_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            quantity: 
              type: integer
            rec_name: 
              type: string
            unit: 
              type: integer
            unit_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
            write_date:
              type: string
              format: date 
            write_uid:
              type: integer
            write_uid_:
              $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        location: 
          type: integer
        location_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
        number: 
          type: string
        rec_name: 
          type: string
        state: 
          type: string
        write_date:
          type: string
          format: date 
        write_uid:
          type: integer
        write_uid_:
          $ref: '../../../api_doc.yaml#/components/schemas/CommonType'
    errors:
      type: object
      nullable: true
    pagination:
      type: object
      nullable: true
    status:
      type: integer
    success_message:
      type: string
      nullable: true

example:
    data:
      company: 1
      company_:
        id: 1
        name: Milestone
      create_date: '2024-08-10T15:27:34.721041'
      create_uid: 1
      create_uid_:
        id: 1
        name: Administrator
      date: '2024-08-10'
      empty_quantity: keep
      id: 1
      lines:
      - create_date: '2024-08-10T15:27:34.721041'
        create_uid: 1
        create_uid_:
          id: 1
          name: Administrator
        expected_quantity: 0
        id: 1
        inventory: 1
        inventory_:
          id: 1
          name: "[1] Output Zone @ 08/10/2024"
        inventory_date: '2024-08-10'
        inventory_location: 2
        inventory_location_:
          id: 2
          name: Output Zone
        inventory_state: draft
        moves: []
        product: 384
        product_:
          id: 384
          name: acetazolamide
        quantity: 1
        rec_name: acetazolamide - 1
        unit: 1
        unit_:
          id: 1
          name: Unit
        write_date: 
        write_uid: 
        write_uid_: {}
      location: 2
      location_:
        id: 2
        name: Output Zone
      number: '1'
      rec_name: "[1] Output Zone @ 08/10/2024"
      state: draft
      write_date: 
      write_uid: 
      write_uid_: {}
    errors: null
    pagination: null
    status: 201
    success_message: null
