      properties:
        create_date: 
            type: string 
            format: date 
        create_uid: 
            type: integer
        create_uid_:
            $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        amputation_date: 
            type: string 
            format: date
        amputation_level: 
            type: string
        body_structure: 
            type: integer
        body_structure_:
            $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        comments: 
            type: string
        etiology: 
            type: string
        healthprof: 
            type: integer
        healthprof_:
            $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        id: 
            type: integer
        limb: 
            type: string
        patient: 
            type: integer
        patient_:
            $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        rec_name: 
            type: string
        side: 
            type: string
        write_date:
            type: string
            format: date 
        write_uid:
            type: integer
        write_uid_:
            $ref: '../../../../api_doc.yaml#/components/schemas/CommonType'
        
      required:
          - 
      example:
          - amputation_date: '2024-08-04'
            amputation_level: tr
            body_structure: 1
            body_structure_:
                id: 1
                name: Brain
            comments: comments here...
            create_date: '2024-08-26T15:23:12.983969'
            create_uid: 1
            create_uid_:
                id: 1
                name: Administrator
            etiology: trauma
            healthprof: 1
            healthprof_:
                id: 1
                name: elyas
            id: 1
            limb: lower
            patient: 4
            patient_:
                id: 4
                name: elyas
            rec_name: '1'
            side: right
            write_date: 
            write_uid: 
            write_uid_: {} 